import type { Formation } from "./types";

// Pitch coordinates: x = 0 (left) → 100 (right), y = 0 (own goal) → 100 (attack).
export const FORMATIONS: Formation[] = [
  {
    id: "4-3-3",
    name: "4-3-3",
    description: "Attacking width. Three forwards create a constant threat.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "RB", role: "RB", label: "RB", x: 85, y: 28 },
      { id: "CB1", role: "CB", label: "CB", x: 62, y: 22 },
      { id: "CB2", role: "CB", label: "CB", x: 38, y: 22 },
      { id: "LB", role: "LB", label: "LB", x: 15, y: 28 },
      { id: "CM1", role: "CM", label: "CM", x: 72, y: 52 },
      { id: "CM2", role: "CM", label: "CM", x: 50, y: 47 },
      { id: "CM3", role: "CM", label: "CM", x: 28, y: 52 },
      { id: "RW", role: "RW", label: "RW", x: 82, y: 80 },
      { id: "ST", role: "ST", label: "ST", x: 50, y: 86 },
      { id: "LW", role: "LW", label: "LW", x: 18, y: 80 },
    ],
  },
  {
    id: "4-4-2",
    name: "4-4-2",
    description: "The classic. Balanced bank of four with a strike partnership.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "RB", role: "RB", label: "RB", x: 85, y: 28 },
      { id: "CB1", role: "CB", label: "CB", x: 62, y: 22 },
      { id: "CB2", role: "CB", label: "CB", x: 38, y: 22 },
      { id: "LB", role: "LB", label: "LB", x: 15, y: 28 },
      { id: "RM", role: "RM", label: "RM", x: 84, y: 55 },
      { id: "CM1", role: "CM", label: "CM", x: 60, y: 50 },
      { id: "CM2", role: "CM", label: "CM", x: 40, y: 50 },
      { id: "LM", role: "LM", label: "LM", x: 16, y: 55 },
      { id: "ST1", role: "ST", label: "ST", x: 62, y: 84 },
      { id: "ST2", role: "ST", label: "ST", x: 38, y: 84 },
    ],
  },
  {
    id: "4-2-3-1",
    name: "4-2-3-1",
    description: "Double pivot shields the back four; a creative ten pulls strings.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "RB", role: "RB", label: "RB", x: 85, y: 28 },
      { id: "CB1", role: "CB", label: "CB", x: 62, y: 22 },
      { id: "CB2", role: "CB", label: "CB", x: 38, y: 22 },
      { id: "LB", role: "LB", label: "LB", x: 15, y: 28 },
      { id: "CDM1", role: "CDM", label: "CDM", x: 62, y: 44 },
      { id: "CDM2", role: "CDM", label: "CDM", x: 38, y: 44 },
      { id: "RW", role: "RW", label: "RW", x: 84, y: 70 },
      { id: "CAM", role: "CAM", label: "CAM", x: 50, y: 66 },
      { id: "LW", role: "LW", label: "LW", x: 16, y: 70 },
      { id: "ST", role: "ST", label: "ST", x: 50, y: 88 },
    ],
  },
  {
    id: "4-5-1",
    name: "4-5-1",
    description: "Midfield overload. Control the centre, starve the opponent.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "RB", role: "RB", label: "RB", x: 85, y: 28 },
      { id: "CB1", role: "CB", label: "CB", x: 62, y: 22 },
      { id: "CB2", role: "CB", label: "CB", x: 38, y: 22 },
      { id: "LB", role: "LB", label: "LB", x: 15, y: 28 },
      { id: "RM", role: "RM", label: "RM", x: 86, y: 56 },
      { id: "CM1", role: "CM", label: "CM", x: 64, y: 50 },
      { id: "CAM", role: "CAM", label: "CAM", x: 50, y: 64 },
      { id: "CM2", role: "CM", label: "CM", x: 36, y: 50 },
      { id: "LM", role: "LM", label: "LM", x: 14, y: 56 },
      { id: "ST", role: "ST", label: "ST", x: 50, y: 88 },
    ],
  },
  {
    id: "3-4-3",
    name: "3-4-3",
    description: "Bold and front-footed. Three at the back, three up top.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "CB1", role: "CB", label: "CB", x: 70, y: 24 },
      { id: "CB2", role: "CB", label: "CB", x: 50, y: 20 },
      { id: "CB3", role: "CB", label: "CB", x: 30, y: 24 },
      { id: "RM", role: "RM", label: "RM", x: 85, y: 52 },
      { id: "CM1", role: "CM", label: "CM", x: 60, y: 50 },
      { id: "CM2", role: "CM", label: "CM", x: 40, y: 50 },
      { id: "LM", role: "LM", label: "LM", x: 15, y: 52 },
      { id: "RW", role: "RW", label: "RW", x: 80, y: 82 },
      { id: "ST", role: "ST", label: "ST", x: 50, y: 88 },
      { id: "LW", role: "LW", label: "LW", x: 20, y: 82 },
    ],
  },
  {
    id: "3-5-2",
    name: "3-5-2",
    description: "Wing-backs provide width; a packed midfield dominates the ball.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "CB1", role: "CB", label: "CB", x: 70, y: 24 },
      { id: "CB2", role: "CB", label: "CB", x: 50, y: 20 },
      { id: "CB3", role: "CB", label: "CB", x: 30, y: 24 },
      { id: "RM", role: "RM", label: "RWB", x: 88, y: 50 },
      { id: "CM1", role: "CM", label: "CM", x: 62, y: 48 },
      { id: "CAM", role: "CAM", label: "CAM", x: 50, y: 62 },
      { id: "CM2", role: "CM", label: "CM", x: 38, y: 48 },
      { id: "LM", role: "LM", label: "LWB", x: 12, y: 50 },
      { id: "ST1", role: "ST", label: "ST", x: 62, y: 86 },
      { id: "ST2", role: "ST", label: "ST", x: 38, y: 86 },
    ],
  },
  {
    id: "5-4-1",
    name: "5-4-1",
    description: "Fortress mode. Five at the back to grind out the result.",
    slots: [
      { id: "GK", role: "GK", label: "GK", x: 50, y: 8 },
      { id: "RB", role: "RB", label: "RWB", x: 88, y: 34 },
      { id: "CB1", role: "CB", label: "CB", x: 68, y: 22 },
      { id: "CB2", role: "CB", label: "CB", x: 50, y: 20 },
      { id: "CB3", role: "CB", label: "CB", x: 32, y: 22 },
      { id: "LB", role: "LB", label: "LWB", x: 12, y: 34 },
      { id: "RM", role: "RM", label: "RM", x: 84, y: 58 },
      { id: "CM1", role: "CM", label: "CM", x: 60, y: 54 },
      { id: "CM2", role: "CM", label: "CM", x: 40, y: 54 },
      { id: "LM", role: "LM", label: "LM", x: 16, y: 58 },
      { id: "ST", role: "ST", label: "ST", x: 50, y: 88 },
    ],
  },
];

export function getFormation(id: string): Formation {
  return FORMATIONS.find((f) => f.id === id) ?? FORMATIONS[0];
}
